### ISSUE TITLE
Don't see any lights anymore

### ISSUE THREAD

**Issue by movedoa** [mzanetti/shine#4]
I was using shine for a few days and it worked great (bg e4.5)
But suddenly it stopped showing me any lights.
It is connected to the bridge.
The iphone app still shows all the lights and works well so i am pretty sure this is not an issue on my side.

I reinstalled the App but nothing changed.

If you need any logs or any other kind of information, let me know.

**Comment by mzanetti** [comment]
Yes, please attach ~/.upstart/cache/com.ubuntu.developer.mzanetti.shine/shine.log.

If you don't know how to access it, install the logviewer app from the store, find shine's log and click the paste button.

**Comment by movedoa** [comment]
http://pastebin.com/mSfE5gFk

**Comment by mzanetti** [comment]
Thanks a lot. Seems your user is not authenticated any more. Will look into it. Sorry for the troubles.

**Comment by muesli** [comment]
Sounds like you recently updated your Hue bridge, which removed all custom-created users on the bridge (this feature isn't support anymore either). You have to use the username/key provided by the bridge upon registration now.

**Comment by mzanetti** [comment]
Yep, I received that email about that. However, IIRC it should only start end of October. Anyhow, about time I'll fix that. Will do that.

**Comment by mzanetti** [comment]
Ok. Version 0.6 should fix this by detecting the situation and allow re-pairing. Also updates pairing mechanism to not include a predefined user name.
